package model;

import java.util.List;

public class Queries {
    //Create tables
    private final static String queryData = "CREATE TABLE DATA(USER_ID NUMBER, MOVIE_ID NUMBER, RATING NUMBER, TIME_STAMP TIMESTAMP, PRIMARY KEY(USER_ID, MOVIE_ID), FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID), FOREIGN KEY(MOVIE_ID) REFERENCES ITEM(MOVIE_ID))";
    private final static String queryGenre = "CREATE TABLE GENRE(NAME VARCHAR2(200), GENRE_ID NUMBER, PRIMARY KEY(GENRE_ID))";
    private final static String queryItem  = "CREATE TABLE ITEM(MOVIE_ID NUMBER, MOVIE_TITLE VARCHAR2(200), RELEASE_DATE VARCHAR2(200), VIDEO_RELEASE_DATE VARCHAR2(200), IMDb VARCHAR2(200), IS_UNKNOWN NUMBER, IS_ACTION NUMBER, IS_ADVENTURE NUMBER, IS_ANIMATION NUMBER, IS_CHILDREN NUMBER, IS_COMEDY NUMBER, IS_CRIME NUMBER, IS_DOCUMENTARY NUMBER, IS_DRAMA NUMBER, IS_FANTASY NUMBER, IS_FILM_NOIR NUMBER, IS_HORROR NUMBER, IS_MUSICAL NUMBER, IS_MYSTERY NUMBER, IS_ROMANCE NUMBER, IS_SCI_FI NUMBER, IS_THRILLER NUMBER, IS_WAR NUMBER, IS_WESTERN NUMBER, PRIMARY KEY(MOVIE_ID))";
    private final static String queryUser = "CREATE TABLE USERS(USER_ID NUMBER, AGE NUMBER, GENDER VARCHAR2(200), OCCUPATION VARCHAR2(200), ZIP_CODE VARCHAR2(200), PRIMARY KEY(USER_ID))";

    public final static String dropTables = "DROP TABLE USERS CASCADE CONSTRAINTS; DROP TABLE ITEM CASCADE CONSTRAINTS; DROP TABLE GENRE CASCADE CONSTRAINTS; DROP TABLE DATA;";

    //Inserts


    public static List<String> getTableQueries(){
        return List.of(queryGenre,queryItem,queryUser, queryData);
    }

    public static List<String> getTableInserts(){
        return List.of();
    }
}
